name: Build Xamarin.iOS app

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: 87434333d2277e5b256e14e14c34b25ff772f4b6
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.20 --android=11.3
    
    - name: Set default Xcode 12.5.1
      run: |
        XCODE_ROOT=/Applications/Xcode_12.5.1.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH

        # create temporary keychain
        security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_PATH

        # import certificate to keychain
        security import $CERTIFICATE_PATH -P $P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
    - name: Setup .NET Core SDK 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: clear cache
      run: nuget locals all -clear
    - name: Debug
      run: |
        ls /Users/runner/.dotnet/sdk/5.0.400
        
    - name: Install dependencies
      run: |
        nuget restore ${{github.workspace}}/osu.sln || echo 'aaa'
        
    - name: Build
      run: msbuild ${{github.workspace}}/osu.iOS/osu.iOS.csproj /p:Configuration=Release /p:Platform=iPhoneSimulator /t:Rebuild
#     - name: Build
#       run: |
#         cd ${{github.workspace}}/osu.iOS
#         dotnet build /p:Configuration=Release /p:Platform=iPhoneSimulator
