name: Build Xamarin.iOS app

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
    
    - uses: actions/checkout@v2
    - name: Set default Xamarin SDK versions
      run: |
        $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.10
    
    - name: Set default Xcode 12.5.1
      run: |
        XCODE_ROOT=/Applications/Xcode_12.5.1.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT

    - name: Setup .NET Core SDK 3.1.412
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.412'

    - name: Install dependencies
      run: nuget restore ${{ github.workspace }}/osu.sln

    - name: Build
      run: msbuild ${{ github.workspace }}/osu.iOS/osu.iOS.csproj /p:Configuration=Debug /p:Platform=iPhoneSimulator /t:Rebuild
